### PR TITLE
Name main plugin file

### PR DESCRIPTION
**Pull request by szepeviktor**
@jchristopher Please see https://developer.wordpress.org/plugins/plugin-basics/

### CODE REVIEW

**Comment by szepeviktor** [comment]
This needs reactivation from **all** existing users :(

**Comment by jchristopher** [comment]
Hi @szepeviktor — I haven't renamed the main plugin file (yet) but can you elaborate on what you mean when you wrote

> This needs reactivation from all existing users :(

Do you mean that updating to `1.6.1` deactivated CMS Tree Page View?

**Comment by szepeviktor** [comment]
WordPress core stores plugins by `directory-name/main-plugin-file-name.php`.
So if you change the main plugin file name in the next release core will say: "plugin not found" and thus not activate your plugin.

**Comment by jchristopher** [comment]
Ok I understand now — renaming the plugin file is not currently part of the plan for that exact reason, and having it be `index.php` (while not considered best practice) is not causing any harm that I am aware of.

If I am incorrect, and the main plugin file name is causing a problem I am not aware of please let me know. Thank you!

**Comment by szepeviktor** [comment]
Okay.
That is a business must.
Although you can move the code from index.php to a properly named main plugin file and say this in index.php:

```php
require dirname( __FILE__ ) . '/cms-tree-page-view.php';
```

**Comment by jchristopher** [comment]
Perhaps I am underestimating the severity here — can you elaborate on what yo mean when you say

> That is a business must.

Thank you!

**Comment by szepeviktor** [comment]
Renaming the main plugin files actually means

- receiving a lot of support questions
- having a lot of bad reviews
- loosing many users

That is why keeping `index.php` is a business must.

**Comment by jchristopher** [comment]
Thank you for following up, @szepeviktor — because there appear to be only downsides to changing the main plugin file name I'm going to close this PR in favor of retaining the existing file structure.

I very much appreciate your PRs so far, thank you!

**Pull request closed without merging**
